# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    app.notification_sender:
        class: App\Service\NotificationSender
        lazy:  true
        arguments: ['@doctrine.orm.entity_manager', '@templating', ' @router']

    app.menu_builder:
        class: App\Menu\Builder
        arguments: ["@knp_menu.factory"]

    app.main_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", MainMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: nav }
    app.user_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", UserMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: user_nav }

    security.access.post_voter:
        class:      App\Security\PostVoter
        public:     false
        tags:
            - { name: security.voter }

    admin.post:
        class: App\Admin\PostAdmin
        arguments: [~, App\Entity\Post, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Post }

    admin.category:
        class: App\Admin\CategoryAdmin
        arguments: [~, App\Entity\Category, RedCodeTreeBundle:TreeAdmin , 'title']
        tags:
        - { name: sonata.admin, manager_type: orm, group: default, label: Category }

    admin.tag:
        class: App\Admin\TagAdmin
        arguments: [~, App\Entity\Tag, ~]
        tags:
        - { name: sonata.admin, manager_type: orm, label: Tag }

    app.pagintaion:
        class: App\Service\PaginationFactory
        autowire: true
        public: true
